### ISSUE TITLE
Replaced GTMHTTPfetcher to GTMSessionFecter and missing the enum value kGTMHTTPFetcherErrorAuthenticationChallengeFailed = -2

### ISSUE THREAD

**Issue by mnang** [google/gtm-session-fetcher#114]
I've replaces GTMHTTPFecther files to GTMSessionFecther files and i'm missing one of the enum value for Authentication error and would like to know if there's any value I can use for the same purpose.

**Comment by thomasvl** [comment]
Because the SessionFetcher is based off NSURLSession instead, the handing of proxies/authentication is different and there isn't a direct mapping.  There are methods exposed to inspect/react to the challenges as they come in, you'll likely need to revisit your code some to see how it makes sense to hook in with these instead.

**Comment by JcChimjj** [comment]
＃114

**Comment by JcChimjj** [comment]
＃114

**Comment by JcChimjj** [comment]
＃114

**Comment by JcChimjj** [comment]
＃114
