### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by JonasGessner** [google/gtm-session-fetcher#157]
Swift Package Manager is now [built into Xcode](https://developer.apple.com/documentation/xcode/creating_a_swift_package_with_xcode) and is already becoming widely adopted by 3rd party libraries. It would be great to see support for SPM here, as this would open up other google libraries (like GTLR) that depend on this library to also use SPM.

**Comment by thomasvl** [comment]
If someone wants to put together a PR for this, we'll need to ensure we figure out how to have CI on it also so it doesn't accidentally get broken in the future.

**Comment by thomasvl** [comment]
Thinking a little more about this, I think SwiftPM might not be able to express things well enough.

The current CocoaPod has three subspecs: _Core_, _Full_, and _LogView_.  The subspecs exist because ObjC doesn't really dead strip, so they allow a developer to pick up the amount needed and not get extra bloat.  From a source POV, since they end up in one module, he `#import` directive work out as they are still a single module name.

While SwiftPM has different products/libraries within a `Package.swift`, they all end up with different names, so the sources would need to know how to differently import the headers to actually build, but since SwiftPM is mainly focused on Swift, there isn't a convention of having some preprocessor symbol one can use for the source to conditionally get the right import.

So for SwiftPM support, it might mean a single library, with everything, and developers lose the option to get say just the _Core_ parts to keep things smaller.

It might be worth checking the Swift Forums for any discussion on bringing better support to SwiftPM for things like this; and if there aren't any, opening a thread to discuss it.

**Comment by JonasGessner** [comment]
You might be able to signal to the source files when they are being compiled through cocoapods by specifying a proprocessor macro to be set when compiled by cocoapods:

```
s.xcconfig = { 'GCC_PREPROCESSOR_DEFINITIONS' => 'USING_COCOAPODS=1' }
```

It should then be possible to import source files directly when when this flag is set (i.e. when using cocoapods) and otherwise (i.e. when compiled with SPM) import the module of the dependency.

**Comment by JonasGessner** [comment]
It also looks like you can define macros in SPM targets: https://developer.apple.com/documentation/swift_packages/csetting. It would be better to import files by default and only import modules when using SPM to allow the source files to be compiled manually.

**Comment by karimhm** [comment]
@thomasvl PR https://github.com/google/gtm-session-fetcher/pull/191 Add support for Swift Package Manager

**Comment by thomasvl** [comment]
Closing this as the PR was landed.
