### ISSUE TITLE
Log Forging

### ISSUE THREAD

**Issue by gopalchinnadurai** [google/gtm-session-fetcher#175]
We have used GTMSessionFetcher 1.2.2 as per our need. Some VAPT points are mentioned in below picture. Kindly help us asap.

**Issue Summary**
The function beginFetchMayDelay:mayAuthorize:() in GTMSessionFetcher.m writes unvalidated user input to the log on line 796. An attacker could take advantage of this behavior to forge log entries or inject malicious content into the log.The identified function writes unvalidated user input to the log. An attacker could take advantage of this behavior to forge log entries or inject malicious content into the log.

**Issue Summary**
<img width="514" alt="Screenshot 2019-12-24 at 4 25 39 PM" src="https://user-images.githubusercontent.com/55129685/71410201-586abb00-266a-11ea-8fc1-1c9e807717ee.png">

**Comment by thomasvl** [comment]
This report doesn't really document where the believe risk is.  The logging feature is meant as meant to help in debugging.  There is a summary html document about all the requests, and then most of the payloads go into individual files.  So while the data logged can come from report places, since the log is just a debugging aid, it isn't really  a risk the log isn't used for anything else except developer inspection.

Also, the report goes on to talk about `RCNUserDefaultManager` which is not part of this library; and the report seems to almost indicate the problem originate there and not in the SessionFetcher.  If you have concerns with that package, I suggest you file it against that package rather than the SessionFetcher.
