### ISSUE TITLE
If allow insecure request we don't need check security

### ISSUE THREAD

**Issue by qiaoyan** [google/gtm-session-fetcher#221]
https://github.com/google/gtm-session-fetcher/blob/3e6489ec459567d735792c81cdb0e41c2cf7fb09/Source/GTMSessionFetcher.m#L568

should it be `&& ![[self class] appAllowsInsecureRequests]); `? I mean if allow insecure request we don't need check security, isn't it?

**Comment by mwyman** [comment]
`NSURLSession` supports both `http` and `ftp`, both of which would be considered insecure; the fetcher permits allowing one but not the other, but checking for either isn't necessary if App Transport Security hasn't been configured to allow arbitrary loads. That's why the check only happens for potentially insecure requests.

**Comment by qiaoyan** [comment]
Yes, but with set allow arbitrary loads to yes it still return error. Am I missing something? Thanks for your kindly reply..
![Screen Shot 2020-12-18 at 8 43 39 AM](https://user-images.githubusercontent.com/1080270/102560565-79df7500-410d-11eb-95dd-ff236c1bd5eb.png)
![Screen Shot 2020-12-18 at 8 44 09 AM](https://user-images.githubusercontent.com/1080270/102560573-7cda6580-410d-11eb-8fa5-69ffa53ff824.png)
