### ISSUE TITLE
App Store Connect warnings about NSPrivacyAccessedAPICategoryFileTimestamp API

### ISSUE THREAD

**Issue by devssun** [google/gtm-session-fetcher#388]
Hello, I use Firebase ios sdk and GoogleSignIn ios sdk.
I updated those SDK to latest version, but App Store Connect is still warning of APIs NSPrivacyAccessedAPICategoryFileTimestamp.

I founded this code, but in your privacy manifest doesn't include NSPrivacyAccessedAPICategoryFileTimestamp.
please add.

```
./SourcePackages/checkouts/gtm-session-fetcher/Sources/LogView/GTMSessionFetcherLogViewController.m:75:                                     includingPropertiesForKeys:@[ NSURLCreationDateKey ]
./SourcePackages/checkouts/gtm-session-fetcher/Sources/LogView/GTMSessionFetcherLogViewController.m:92:      [url1 getResourceValue:&date1 forKey:NSURLCreationDateKey error:NULL];
./SourcePackages/checkouts/gtm-session-fetcher/Sources/LogView/GTMSessionFetcherLogViewController.m:93:      [url2 getResourceValue:&date2 forKey:NSURLCreationDateKey error:NULL];
```

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc

**Comment by thomasvl** [comment]
> I use Firebase 10.24.0 version and this library has dependency GTMSessionFetcher 3.3.1. Firebase need to update dependency version or .. is it okay just update library in my xcode?

You'll have to look at all your direct and transitive dependencies to figure if something is casing it to be pinned to an older version or if you just need to let cocoapods update your dependencies.  As to manually updating it, again, that depends on your dependencies and if someone is preventing updates for a specific reason.

Closing this out, since the library has been annotated, and it appears to be your setup that isn't allowing current versions with privacy manifest.
