### ISSUE TITLE
Use fetcher to download big files with api v3?

### ISSUE THREAD

**Issue by gerchicov-bp** [google/gtm-session-fetcher#52]
I tried to download a large file (>30mb). It is impossible simply to get ```webContentLink``` property value and to use it as a link in ```fetcherWithURLString:``` method. Because they show html page with a confirmation button.

**Comment by thomasvl** [comment]
I'm assuming you mean the Drive API?  The fetch has no limits, so it seems like something on the Drive side.  The [Drive example](https://github.com/google/google-api-objectivec-client-for-rest/tree/master/Examples/DriveSample) uses the Export api call to download, you might want to try that instead.

**Comment by gerchicov-bp** [comment]
I had the following code with API v2:
`GTMHTTPFetcher *fetcher = [fetcherService fetcherWithURLString:downloadUrl];`
Now I have the following one with API v3:
`GTMSessionFetcher *fetcher = [fetcherService fetcherWithURLString:downloadUrl];`

The problem is where to get this ```downloadUrl``` for big files or what to use instead of it for API v3.

Again, NOTE: ```downloadUrl``` is taken as ```-[GTLFileDrive webContentLink]``` and it works for small files and it seems there are no more suitable properties which can store the URL/link value. So I ask how to replace it without of replacing ```GTMSessionFetcher```

**Comment by thomasvl** [comment]
Again, I don't think anything has to do with the fetcher here, it sounds like the issue is on the drive UI side.  Check the sample I linked to before, `-[DriveSampleWindowController showDownloadSavePanelExportingToPDF:]` shows how to download a PDF or the original file (if the format supports it).

The [Drive v3 docs](https://developers.google.com/drive/v3/web/about-sdk) has links for a G+ community and Stack Overflow discussions you can also try posting on.
