### ISSUE TITLE
Add target for static library

### ISSUE THREAD

**Issue by erickoledadevrel** [google/gtm-session-fetcher#9]
For iOS developers that wish to use this library in their application, and don't want to intermingle the source code, it would be great if the project contained a target for a static library.

**Comment by thomasvl** [comment]
Just to be clear so you aren't in favor of CocoaPods?  (We're trying to figure out how to support both camps)

**Comment by erickoledadevrel** [comment]
No, a CocoaPod would be much preferred. But in lieu of that it seems simple to add a static library target, which is what the Google APIs Objective-C library provides today.

**Comment by pr0gramm3r8hai** [comment]
followed instrucrtion of  https://developers.google.com/google-apps/calendar/quickstart/ios?ver=swift but cannot find "GTMSessionFetcher/libGTMSessionFetcherLib.a" file and the clone process downloads GTMCore and GTMSessionFetcherCore instead of GTM and GTMSessionFetcher projects ! Your instruction is not updated its all MESH !

**Comment by erickoledadevrel** [comment]
Given that there is now an iOS Framework available there is no longer a need for a static library. Closing this issue.
